version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - apt-get update -y
      - apt-get install -y maven
      - apt-get install -y ant
  build:
    commands:
      - ant -Doauth2.clientId=${ClientId} -Doauth2.clientSecret=${ClientSecret}
      - mvn install
  post_build:
    commands:
      - mvn package

artifacts:
  files:
    - azure-1.0-SNAPSHOT.jar
  base-directory: 'target'